---
- name: test
  hosts: sisfo
  gather_facts: no
  serial: 8
  # gather_timeout: 60
  connection: network_cli
  ignore_errors: no
  gather_facts: no
  tasks:
    - name: Gather all legacy facts
      ios_facts:
        gather_subset: all
